### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by Archcry** [edv/docker-spotweb#11]
Currently this docker container only supports mysql databases, would adding pdo_postgres (or whatever it's called) to the Dockerfile be enough to get postgres support?

**Comment by edv** [comment]
Okay, haven't really looked at this repo for a long time :) so, finally, about 2 years after you asked this question I have a response :)

I added support for Postgres and SQLite in a recent commit. If this is still relevant, let me know if it works (as I haven't tested both, just added the required php extensions, and the Spotweb installer shows all is well and supported now).

**Comment by Archcry** [comment]
I'll be trying it out sometime :D
