### ISSUE TITLE
Mounting /config	doesn't work, no files in mounted folder. 

### ISSUE THREAD

**Issue by FranktV82** [edv/docker-spotweb#18]
Mounting /config	doesn't work, there are no files in mounted folder.  I mounted /config to /share/data/Spotweb. There are no files in the folder on the host. I was hoping to find some logfiles.

In different docker containers like home assistant this is working on my Qnap.

![image](https://user-images.githubusercontent.com/40358301/41557650-98179d44-733e-11e8-9917-5149e52fad90.png)

**Comment by edv** [comment]
The /config directory is not used for this image (it's something that I forgot to removed when using one of my other Docker image set-ups as the base for this one).

I am currently working on a new base image with several improvements. What kind of log files were you looking for? maybe I can do something with that in the new setup.

**Comment by FranktV82** [comment]
I was looking for spotweb logging, because the update did not work. There should be a spotweb.log, but I can't find in inside the container. Anyway, I found a crontab log where I found out there was een problem with my usenet account. I fixed it and now the update works :). Thanks for your fast support.

**Comment by edv** [comment]
Just released new version with the volumes removed (as they were not used), will close this one, let me know if you encounter any future problems
