### ISSUE TITLE
noob hulp

### ISSUE THREAD

**Issue by bafplus** [edv/docker-spotweb#21]
Hoi Erik!

Dit ziet er zeer goed uit!

Mocht je zin en tijd hebben, zou je deze noob kunnen helpen met wat vraagjes?

Beste is via telegram @bafplus

**Comment by Freekers** [comment]
Deel je vragen hier, zodat anderen je kunnen helpen en ervan kunnen leren.

**Comment by edv** [comment]
Zoals Freekers aangaf, eventuele vragen kunnen het best hier gesteld worden.
