### ISSUE TITLE
Bad Address mysql

### ISSUE THREAD

**Issue by kennethhaspeel** [edv/docker-spotweb#24]
i just wanted to test with default settings. But after the command `docker run -p 8080:80 --name spotweb -d -v /etc/localtime:/etc/localtime:ro erikdevries/spotweb`
spotweb isn't accessible.
When I look at logs from docker-spotweb i see this over and over:
`[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 35-waitforsql: executing...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...
nc: bad address 'mysql'
Waiting for database connection at host 'mysql:3306'...`

**Comment by edv** [comment]
I will update the documentation, it isn't too clear on how to run Spotweb, as it always needs an external (MySQL) database server. The easiest way is to use docker-compose, but when you already run an external database server (outside of Docker) you can use environment variables to connect to the given server.

So for now, it's easiest to check the README and follow the steps beneath "Quick setup using docker compose".

**Comment by kennethhaspeel** [comment]
I'm just starting with docker and i wasn't really clear to me. I used the docker-compose after i posted the above and then i saw the light ;-) 
To use the "docker run .." command i already have to have a database server in docker or otherwise.
With the compose command the database setup is included.

Should have known that
