### ISSUE TITLE
possible to disable the chown step when starting up

### ISSUE THREAD

**Issue by fryelectro** [edv/docker-spotweb#31]
HI,

Let me explain. I mount the docker folder /app/cache to a local folder which contains all the cache gathered in the past. 
When the docker starts, I see it hangs for a very long time in chowning the cache folder since it's rather big and file I/O is maybe slower due to mounting to an extra folder.

My question now: is it possible to disable this chown step (maybe foresee a environment variable which disables this in the startup script?) or can I edit it myself? (not being the docker expert here)

thx

**Comment by edv** [comment]
It is possible to disable this yourself, see the 30-config file in the project, but beware you can mess things up. I haven't tested and/or researched the possible impact of this (but probably it will not do anything weird when it has run at least one time)
