### ISSUE TITLE
Error: Validating index idx_spots_l

### ISSUE THREAD

**Issue by kennethhaspeel** [edv/docker-spotweb#32]
On a fresh "install" i use docker-compose but i'm getting an error on the setup of the database:

![Image of Error](https://i.imgur.com/Xuj7EVj.png)

**Comment by edv** [comment]
Sadly Spotweb itself seems to be broken, I will have a look at it and revert to an older release until this is resolved.

**Comment by edv** [comment]
Code is reverted and it should work again. Will check from time to time to see if the master branch for Spotweb is working again

**Comment by kennethhaspeel** [comment]
My bad
Thanks for the fast replies
