### ISSUE TITLE
Receiving net::ERR_INCOMPLETE_CHUNKED_ENCODING for JS

### ISSUE THREAD

**Issue by KoningFloris** [edv/docker-spotweb#40]
FYI

I was getting the error "net::ERR_INCOMPLETE_CHUNKED_ENCODING" for the URL page=statics&type=js&lang=en_US&mod=1563263890

I solved it with the answer here:
https://stackoverflow.com/questions/29789268/neterr-incomplete-chunked-encoding-nginx

My solution was a blanket chmod -R 7777 * on the /var/lib/nginx folder.
A more elegant solution is likely in the cards.

**Comment by edv** [comment]
A lot has changed since this comment. Right now this seems to work, let me know if you do still encounter problems
