### ISSUE TITLE
Compose stops (it seems)

### ISSUE THREAD

**Issue by roeiegans** [edv/docker-spotweb#43]
Hello,

I used the "docker-compose -f docker-compose-x86.yml up" option. The containers are created, but it seems like the "script" just stops running at this point:

_Attaching to docker-spotweb-master_mysql_1, docker-spotweb-master_spotweb_1
mysql_1    | WARNING: no logs are available with the 'db' log driver
spotweb_1  | WARNING: no logs are available with the 'db' log driver_

Don't know if that's really the issue, after googling, but at least the spotweb-site isn't available at that point. Hope you can help me out here. I'm not that good with docker, that's why I used the compose file. With the database setup this is a bit more complex for me at least than e.g. sabnzbd was. It is docker on a Synology NAS, so I don't use localhost to access it, instead I use the NAS-ip with port 8080.

**Comment by edv** [comment]
Sorry for the late response, I don't work on this project too much anymore.

Did you resolve the problem? It could take a while before you can access Spotweb when first starting (as the database needs to be build up the first time).

If not, you can try to rebuild the image and try again.
