### ISSUE TITLE
No spots stored in the DB

### ISSUE THREAD

**Issue by Smiggel** [edv/docker-spotweb#47]
I tried the docker image with a new stack. I was able to install Spotweb and set it up.

However, when retrieving spots, I notice that there is nothing (spots) stored in the database. The credentials are correct, as other settings are saved in the DB (MariaDB 5 & 10). However, the spots are never stored. 

Anyone else experiencing this issue?

**Comment by edv** [comment]
A lot has changed since this comment. Right now this seems to work, let me know if you do still encounter problems
