### ISSUE TITLE
Ownsettings.php usage

### ISSUE THREAD

**Issue by Fietspomp86** [edv/docker-spotweb#49]
Hey,

Thanks for the great work of making this Spotweb Docker.

For my Spotweb I used an ownsettings.php, for various options/reasons.
In the readme I didn't find an instruction how-to map it with this container, perhaps adding it for other people is an option?

Right now I've mapped the following in my docker-compose.yaml and this works fine:
`    volumes:`
`      - /mnt/data/docker/spotweb/ownsettings.php:/app/ownsettings.php`

**Comment by edv** [comment]
Thanks for the tip, I included it in the documentation
