### ISSUE TITLE
Amend the Cron Sheduling?

### ISSUE THREAD

**Issue by DrFrankensteinUK** [edv/docker-spotweb#50]
Hey I recently swapped one of my Synology guides over to your container image as it make things much easier to set up. However I have had a question relating to the Cron. Is there any way to amend it's frequency?

Appreciate your work.

https://drfrankenstein.co.uk/2023/06/11/spotweb-in-container-manager-on-synology-nas/

Also wanted to mention I do a split of coffee money I get across the year to anyone who I featured in a guide so around October I will ping you part of the split if you have Github Sponsors enabled. 

Thanks

**Comment by DrFrankensteinUK** [comment]
Hey @edv - Sorry to bump but would this be possible to amend via an environment variable rather than have the hard 5 mins updates. I have had a couple of users ask as they allow their drives to hibernate and wanted to do an update daily.

**Comment by edv** [comment]
Very good idea, I just implemented this and pushed it! I update the documentation on how to change the update interval in the docs. Let me know if you run into any problems.

## Change Spotweb update interval

- By default Spotweb will update every 5 minutes
- Change the `CRON_INTERVAL` environment variable to any valid cronjob expression (see e.g. https://cron.help/ for more information, default 5 minute interval is configured in the docker-compose.yml file as an example)
- Restart the Spotweb Docker container (during start-up it will display the current configured update interval)

**Comment by DrFrankensteinUK** [comment]
Thanks much appreciated – let me know your Paypal or something I will ping over some £'s in a couple of weeks.

**Comment by edv** [comment]
Thanks for the offer, but that's not necessary 👍 (if you still have some £ to spare, do wire it to a charity)
