### ISSUE TITLE
Initial install only fills spots from date of setup

### ISSUE THREAD

**Issue by DrFrankensteinUK** [edv/docker-spotweb#51]
Hey sorry back again, we seem to be seeing a bug and I am not sure if it's from here or upstream as I have seen this on other containers as well. 

By default Spotweb seems to be using 'today' as the default date to pull spots from so no backlog is pulled. And when amending the date back to November 2009 from the UI the database does not change. 

If I manually flush tables (might be overkill) and then manually amend the 'Retrieve_Newer_Than' to 1257030000 in the Settings table everything then pulls correctly.

Happy to do any testing required to get this working as it seems to do it on every fresh install. 

Tables I flush with Foreign Key checks disabled are:

    cache
    commentsfull
    commentsposted
    commentsxover
    moderedringbuffer
    reportsposted
    reportsxover
    spots
    spotsfull
    spotstatelist
    usenetstate

**Comment by lennyg1** [comment]
For anyone else finding this at some point. I just ran the following command after changing the Retrieve_Newer_Than date in the database settings table. Setting this through frontend didn't do much for me. The retro command should only be run once and will take a while depending on what you set it to.

`docker exec spotweb /usr/bin/php /app/retrieve.php --retro`

**Comment by DrFrankensteinUK** [comment]
I have noticed this is taking place on every fresh install - I will do some investigating on if there is a way to stop the behaviour.

**Comment by DrFrankensteinUK** [comment]
Apologies I will get back to this!

**Comment by pic16f876** [comment]
> For anyone else finding this at some point. I just ran the following command after changing the Retrieve_Newer_Than date in the database settings table. Setting this through frontend didn't do much for me. The retro command should only be run once and will take a while depending on what you set it to.
> 
> `docker exec spotweb /usr/bin/php /app/retrieve.php --retro`

This worked perfectly!

**Comment by DrFrankensteinUK** [comment]
> > For anyone else finding this at some point. I just ran the following command after changing the Retrieve_Newer_Than date in the database settings table. Setting this through frontend didn't do much for me. The retro command should only be run once and will take a while depending on what you set it to.
> > 
> > `docker exec spotweb /usr/bin/php /app/retrieve.php --retro`
> 

I have a mini guide just to save typing up in here. 

https://drfrankenstein.co.uk/spotweb-not-backfilling/
> how do i change date in db?

**Comment by modparts** [comment]
> > > For anyone else finding this at some point. I just ran the following command after changing the Retrieve_Newer_Than date in the database settings table. Setting this through frontend didn't do much for me. The retro command should only be run once and will take a while depending on what you set it to.
> > > `docker exec spotweb /usr/bin/php /app/retrieve.php --retro`
> 
> I have a mini guide just to save typing up in here.
> 
> https://drfrankenstein.co.uk/spotweb-not-backfilling/
> 
> > how do i change date in db?

Thank you very much, very helpfull and glad i got it working.
