### ISSUE TITLE
Container from 2 days ago not pulling releases

### ISSUE THREAD

**Issue by DrFrankensteinUK** [edv/docker-spotweb#52]
Hey

Your update from 3 weeks back with the Cron schedule has been working perfectly – however it seems like the version pushed 2 days ago has a bug as upon setup nothing is pulled. I tested this myself and had a couple of people on Discord with exactly the same issue. 

I can spin up fresh containers to help find the issue to help out. Not sure if you have experienced any problems at all?

**Comment by edv** [comment]
Can you maybe provide a bit more information? E.g. does this only occur on a fresh installation? or did your already set-up and running environment stop updating? or did you maybe change the newly introduced `CRON_INTERVAL` env. variable? (and with what value)

**Comment by edv** [comment]
Follow up with my findings so far:

- Set up local environment (`make up`), configured NNTP server and waited, update started and couple of minutes later I see the first results in the Spotweb interface
- My long time running Spotweb instance also still updates (every 5 minutes)

Do you maybe see errors in the log while running Spotweb? or see the line "NNTP server not configured, skipping retrieval of new headers" (which would suggest no NNTP server is configured, or at least cannot be seen by the update script that is used)

**Comment by DrFrankensteinUK** [comment]
Hi - I will investigate a bit further during the day tomorrow with a fresh install and see if the issue persists at all. I had seen on my Personal setup nothing pulled for around 10 days (I don't often go on the UI) and then had a couple of people with fresh installations on Discord with issues getting things pulled. 

We let you know tomorrow :)

**Comment by PeebzNL** [comment]
I was one of "the people with issues";  the latest version didn't pull spots/retriever didn't fire up.
Previous version (sha-7da5664, with cron-update?) pulled the spots for 2 days. But fixed by dr.frankenstein. Mariadb now fully filled with spots.
But the update is still every 5 minutes, independend of crons-settin ('0 * * * *' or '*/60 * * * *')

**Comment by edv** [comment]
@PeebzNL can you check the output when you start the container? It should mention "Spotweb Update Cronjob" with the value below it, e.g. "Update interval:    */1 * * * *"

As stated in the README, the default is: */5 * * * *

**Comment by PeebzNL** [comment]
There is no mention of cronjob in the log after stop/start of container.
None whatsoever.

**Comment by DrFrankensteinUK** [comment]
OK I did a whole write-up on the back of multiple installs and then realised I may be at fault so deleted it!

This is completely my fault! I formatted the cron incorrectly!

CRON_INTERVAL='*/7 * * * *'
vs
CRON_INTERVAL=*/7 * * * *

Sorry!

-

On my multiple installs I do see that no backfill takes place before the day of install - I will update in the other issue I raised..

**Comment by DrFrankensteinUK** [comment]
Not directly related, but the official MariaDB doesn't seem to have a health check built in causing the database to not be available upon first start up. So likely going to move to the LinuxServer build to see if this mitigates the initial start up issue

**Comment by PeebzNL** [comment]
I've changed the cron-setting, quotes removed. Now value is  0 * * * *  (incl. stop/start container).
But retriever still fires up every 5 minutes. Log doesn't mention cron-settings.
Only:  
2023/10/13 16:45:33,stderr,services-up: info: copying legacy longrun cron (no readiness notification)

**Comment by PeebzNL** [comment]
For reference: the spotweb version I am running is sha-7da5664

**Comment by edv** [comment]
> Not directly related, but the official MariaDB doesn't seem to have a health check built in causing the database to not be available upon first start up. So likely going to move to the LinuxServer build to see if this mitigates the initial start up issue

I'm curious what problem you run into by this lack of health check, as the Spotweb container has a built in polling mechanism that tries to connect to the MySQL server until it is ready (see "Waiting (5 seconds) for database connection at host 'mysql:3306'..." in the logs). Let me know, so the Spotweb image can maybe be improved to handle unavailable database servers in a better way.

**Comment by edv** [comment]
> I've changed the cron-setting, quotes removed. Now value is 0 * * * * (incl. stop/start container). But retriever still fires up every 5 minutes. Log doesn't mention cron-settings. Only: 2023/10/13 16:45:33,stderr,services-up: info: copying legacy longrun cron (no readiness notification)

I just checked and the release you use does not include this feature, you have to use at least tag `sha-b9190aa` to be able to configure the update interval.

**Comment by PeebzNL** [comment]
That explains it,
Switched to -latest- yesterday. It’s running smoothly now.
