### ISSUE TITLE
Local blacklist

### ISSUE THREAD

**Issue by owanneke** [edv/docker-spotweb#56]
Feature request:

Is it possible to add a local blacklist (mapped folder into the docker image?) and to add spotters to it from the web UI?

Is there any information available on the existing external blacklist format?
i.e. what is the value used to block a spotter?

e.g.
<Key Name="Aeon">
3aZW/B4RCV1I5bVNyvs3N10MbGgCYttvILMBUZM3SUelQgOcUxS/aFI8ZrAzHp7z    <-- this thing
</Key>

**Comment by edv** [comment]
This repository contains just a Docker "wrapper" for Spotweb (and contains no actual code). The official Spotweb repo is found at https://github.com/spotweb/spotweb maybe they can help you further on the blacklist details.
