### ISSUE TITLE
SpotWeb v0.68.36.34 on PHP v8.3.6 crashed object

### ISSUE THREAD

**Issue by rayray4105** [edv/docker-spotweb#58]
Hi,

Today I updated Spotweb to the latest version but now it is not working anymore. Did I do something wrong?

SpotWeb v0.68.36.34 on PHP v8.3.6 crashed object(Exception)#7 (7) { ["message":protected]=> string(44) "Unknown database engine () factory specified" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(28) "/app/lib/dbeng/dbeng_abs.php" ["line":protected]=> int(22) ["trace":"Exception":private]=> array(3) { [0]=> array(5) { ["file"]=> string(22) "/app/lib/Bootstrap.php" ["line"]=> int(148) ["function"]=> string(12) "getDbFactory" ["class"]=> string(9) "dbeng_abs" ["type"]=> string(2) "::" } [1]=> array(5) { ["file"]=> string(22) "/app/lib/Bootstrap.php" ["line"]=> int(42) ["function"]=> string(13) "getDaoFactory" ["class"]=> string(9) "Bootstrap" ["type"]=> string(2) "->" } [2]=> array(5) { ["file"]=> string(14) "/app/index.php" ["line"]=> int(19) ["function"]=> string(4) "boot" ["class"]=> string(9) "Bootstrap" ["type"]=> string(2) "->" } } ["previous":"Exception":private]=> NULL } Unknown database engine () factory specified

**Comment by edv** [comment]
Quite a bit was changed recently around database configuration, it should however not break anything.

Can you share how you start the Docker container? (your docker-compose.yml or the Docker command). I'm curious if (and what) environment setting you have configured.

**Comment by rayray4105** [comment]
I did not use a compose.yml unfortunately.

**Comment by edv** [comment]
That is also fine, but can you give some more information on how you start the container? I just tried several combinations of settings, but I did not manage to get it to break. It would help me in debugging what might have gone wrong in the recent changes I made.

**Comment by rayray4105** [comment]
I am running the docker official image for mariadb. https://registry.hub.docker.com/_/mariadb/

**Comment by rayray4105** [comment]
my settings are pretty standard I think.

![image](https://github.com/edv/docker-spotweb/assets/43954547/9df67d34-58d8-4264-a1c6-10801d4f7a92)

**Comment by edv** [comment]
The only difference I see is that DB_ENGINE is not configured, but that should default to MySQL (pdo_mysql). I tried to replicate the problem, but it might have to do with the Docker version you are running on Synology.

I made some changes which _should_ resolve this, can you update to the latest Docker image and see if it works for you?

And if it does not work, can you try adding another environment variable called `DB_ENGINE` with value `pdo_mysql`?

**Comment by edv** [comment]
Good to hear, if you encounter other problems, let me know
