### ISSUE TITLE
Can not add to prowlarr 

### ISSUE THREAD

**Issue by Tonynks** [edv/docker-spotweb#60]
I'm trying to add the indexer to prowlarr using my spotweb subdomain.  I keep getting this error.  

This page contains the following errors:
error on line 21 at column 66: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.
Spotweb Index Spotweb Index API Results en-gb Admin@mydomain.net (Tbone) Spotweb Index SpotWeb Index API Results De Lift (1983) - 4K Topaz Enhanced - H265 - NLsub GSNNDYfzmT4sj9VZgYUx3@spot.net

**Comment by Slevin90** [comment]
I've had problems with prowlarr too.
adding directly to the other arr's (readarr, sonarr, radarr) does work.  

This might be a good workaround for you

**Comment by geolaw** [comment]
new user of this container.
I previously had a custom container I built based on Fedora 37 or something like that.
so apache with php
I had to add this to the .htaccess file to make things work :+1: 
$ cat ../spotweb3/www/.htaccess 
<IfModule mod_rewrite.c>
	RewriteEngine on  
	RewriteCond %{REQUEST_URI} !api/  
	RewriteRule api/?$ index.php?page=newznabapi [QSA,L]  
</IfModule>


I found this that converts the file .. 
https://winginx.com/en/htaccess

# nginx configuration by winginx.com

location  api/ {
}

location / {
  rewrite api/?$ /index.php?page=newznabapi break;
}

but not sure if this needs to go in the main nginx config or what .. still testing it myself.

**Comment by geolaw** [comment]
Confirming that once I got my user's api key and plugged it into prowlarr, the .htaccess change with the nginx format seems to have done it, I test my spotweb indexer in prowlarr and get a green check mark :)

**Comment by geolaw** [comment]
yeah, prowlarr at least sees spotweb now but searches are failing.

In prowlarr I get a "green check" after testing my instance of spotweb, then I go to search, search for highlander and select just the spotweb indexer.  It returns no results,  I get this in the container logs : 
~~~
2024/07/22 20:46:18 [error] 105#105: *289 FastCGI sent in stderr: "PHP message: SpotWeb Exception occured: HY000: 1: fts5: syntax error near "+"" while reading response header from upstream, client: 10.88.0.1, server: _, request: "GET /api?t=search&extended=1&apikey=_MY_KEY_&q=highlanders&limit=100&offset=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.29.7:8085"
~~~
and then the prowler spotweb indexer goes into an error.

If I intentionally change a digit in my api key I get a different result  - access denied. 

May need to ask the upstream spotweb github i think.

**Comment by geolaw** [comment]
Sorry to keep spamming here.
I just swapped my setup over to use mysql instead of sqlite ... the prowlarr error goes away, so it must be something with how spotweb constructs the sql queries against sqlite

**Comment by edv** [comment]
Maybe this has been resolved, but using the MySQL setup Prowlarr seems to work okay with me, what I did:

- I did not make any changes to the Spotweb image (just using erikdevries/spotweb)
- In spotweb create a new user and copy the API key
- In Prowlarr I pick "generic NewzNab" and pointed it to the IP + port where I host Spotweb (e.g.     http://192.168.10.72:9007) including the API key
- Everything seems to work okay after this (although I do not use Prowlarr, so I might have missed something)

**Comment by geolaw** [comment]
Yes, I can confirm going with mysql also fixed it for me.
I think the underlying problem is sqlite is getting sent a query with a + sign in it that it does not like

The php error is : syntax error near "+"" while reading response header

So maybe something minor in the "+" support between mysql and sqlite?
